import type { Metadata } from "next";
import { Plus_Jakarta_Sans , Noto_Sans_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css"

const jakarta_Sans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets : ["latin"]
})

const rubik_mono = Noto_Sans_Mono({
  weight:"400",
  variable:"--font-noto-mono"
})

export const metadata: Metadata = {
  title: "SMK- Skill Bridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jakarta_Sans.variable} ${rubik_mono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-amber-200">{children}</body>
    </html>
  );
}
